### PR TITLE
Version bump mcl

### PR DESCRIPTION
**Pull request by JanBobolz**
Using a newer version of mcl (newest _release_ (v1.51) had test errors, so I've referenced the current mcl `master` branch commit). 

It works on my (macOS) machine. 

Can you please test `./install_mcl.sh` on your machines, @rheitjoh , @feidens ?

### CODE REVIEW

**Comment by feidens** [comment]
```c++ mcl_wrap.cxx -o ../../lib/libmcljava.dylib -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -Wundef -m64 -I include -I test -fomit-frame-pointer -DNDEBUG -fno-stack-protector -O3  -DMCL_USE_VINT -DMCL_DONT_USE_OPENSSL -fPIC -I/Users/fabianeidens/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/include/darwin -I/Users/fabianeidens/Library/Java/JavaVirtualMachines/openjdk-15.0.2/Contents/Home/include -I ../../include -I -Wno-strict-aliasing ../../lib/libmcl.a   -m64  -shared
ld: warning: object file (../../lib/libmcl.a(x86-64.o)) was built for newer macOS version (11.0) than being linked (10.15)
javac MclTest.java
cd ../../lib && LD_LIBRARY_PATH=../lib: java -classpath ../ffi/java MclTest
libName : libmcljava.dylib
curve=BN254
OK : x != y
OK : x == z
OK : x == 5
OK : x == 3
OK : x == 9
OK : x == 12
OK : x == 18
OK : x == ff
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void com.herumi.mcl.MclJNI.inv__SWIG_0(long, com.herumi.mcl.Fr, long, com.herumi.mcl.Fr)'
	at com.herumi.mcl.MclJNI.inv__SWIG_0(Native Method)
	at com.herumi.mcl.Mcl.inv(Mcl.java:21)
	at MclTest.testCurve(MclTest.java:48)
	at MclTest.main(MclTest.java:171)
make: *** [test_mcl] Error 1
```
🚨 does not work

**Comment by feidens** [comment]
macOS 10.5 is the problem

**Comment by feidens** [comment]
Sorry. The real reason was that there was an old libmcljava already installed.

**Comment by rheitjoh** [comment]
Seems to work fine for me, mclwrap tests run through as well. 
The readme still mentions the whole v1.26 thing. I think we can wait with updating that for when the mcl version we are using gets its own version string. Wouldn't want to refer to a commit number in the readme.

**Review by rheitjoh — APPROVED** [review]

**Comment by JanBobolz** [comment]
Waiting for new release so that we don't have to reference a commit hash.

**Pull request merged**
